# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c97587a5470148fc8efccf03f8866077b00555e5808a21723c3198e8e44666ce7e9ae9ac201599548af719d6f9c345e443f7e075fa8248e49301dc45849d07c

test:
  secret_key_base: a736cc5336bf9b1bd863a4b04f026d11b78a8108a7650a4977e3c70cf5e5375892980932b3c38b53a5ffb3741ffc3f8469e2dfe33dfea7d0019a1a788541e17e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
